version: "3"
services:
        camping-arena:
            container_name: camping-arena
            image: shivam2021123/camping-arena
            restart: always
           
            ports:
              - "3000:3000"
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27017:27017'
